# Generated by Django 6.0.1 on 2026-01-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_allocations', to='resources.resource'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='events_even_start_d_b72861_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end_datetime'], name='events_even_end_dat_53a75f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['primary_club'], name='events_even_primary_fffff8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcollaborator',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_879d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcollaborator',
            index=models.Index(fields=['role'], name='events_even_role_489c40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcollaborator',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_8518cd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['rating'], name='events_even_rating_8e40a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventfeedback',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_8164b3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['status'], name='events_even_status_bdf692_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['registered_at'], name='events_even_registe_659dc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventresource',
            index=models.Index(fields=['event', 'resource'], name='events_even_event_i_e6069f_idx'),
        ),
    ]
