# Generated by Django 6.0.1 on 2026-01-26 05:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_initial'),
        ('events', '0001_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('event_approval', 'Event Approval'), ('event_registration', 'Event Registration'), ('event_update', 'Event Update'), ('event_reminder', 'Event Reminder'), ('club_invitation', 'Club Invitation'), ('club_approval', 'Club Approval'), ('resource_booking', 'Resource Booking'), ('booking_approval', 'Booking Approval'), ('booking_reminder', 'Booking Reminder'), ('message', 'New Message'), ('announcement', 'Announcement'), ('system', 'System Notification'), ('other', 'Other')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App Notification'), ('sms', 'SMS')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('event_approval', 'Event Approval'), ('event_registration', 'Event Registration'), ('event_update', 'Event Update'), ('event_reminder', 'Event Reminder'), ('club_invitation', 'Club Invitation'), ('club_approval', 'Club Approval'), ('resource_booking', 'Resource Booking'), ('booking_approval', 'Booking Approval'), ('booking_reminder', 'Booking Reminder'), ('message', 'New Message'), ('announcement', 'Announcement'), ('system', 'System Notification'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('message_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.messagethread')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
