# Generated by Django 6.0.1 on 2026-01-26 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubannouncement',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='clubannouncement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubdocument',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='clubdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubinvitation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='clubinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['slug'], name='clubs_club_slug_9373ca_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['club_type'], name='clubs_club_club_ty_dc6c54_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['status'], name='clubs_club_status_23d2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['created_at'], name='clubs_club_created_8b63d9_idx'),
        ),
        migrations.AddIndex(
            model_name='clubannouncement',
            index=models.Index(fields=['club', 'is_pinned', 'created_at'], name='clubs_cluba_club_id_4ba1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='clubdocument',
            index=models.Index(fields=['club', 'document_type'], name='clubs_clubd_club_id_60f57c_idx'),
        ),
        migrations.AddIndex(
            model_name='clubdocument',
            index=models.Index(fields=['is_public'], name='clubs_clubd_is_publ_228d68_idx'),
        ),
        migrations.AddIndex(
            model_name='clubinvitation',
            index=models.Index(fields=['token'], name='clubs_clubi_token_a3a146_idx'),
        ),
        migrations.AddIndex(
            model_name='clubinvitation',
            index=models.Index(fields=['email', 'status'], name='clubs_clubi_email_22e324_idx'),
        ),
        migrations.AddIndex(
            model_name='clubinvitation',
            index=models.Index(fields=['expires_at'], name='clubs_clubi_expires_2db913_idx'),
        ),
    ]
