# Generated by Django 3.2.25 on 2026-01-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='club',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
