# Generated by Django 6.0.1 on 2026-01-26 05:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('users_by_role', models.JSONField(default=dict)),
                ('total_clubs', models.IntegerField(default=0)),
                ('active_clubs', models.IntegerField(default=0)),
                ('pending_clubs', models.IntegerField(default=0)),
                ('club_membership_stats', models.JSONField(default=dict)),
                ('total_events', models.IntegerField(default=0)),
                ('events_by_type', models.JSONField(default=dict)),
                ('events_by_status', models.JSONField(default=dict)),
                ('total_registrations', models.IntegerField(default=0)),
                ('avg_event_rating', models.FloatField(default=0.0)),
                ('total_resources', models.IntegerField(default=0)),
                ('resource_utilization', models.FloatField(default=0.0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('booking_success_rate', models.FloatField(default=0.0)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('registration_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('avg_club_memberships', models.FloatField(default=0.0)),
                ('avg_event_registrations', models.FloatField(default=0.0)),
                ('user_engagement_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['snapshot_type', 'period_start'], name='analytics_a_snapsho_7392db_idx'), models.Index(fields=['created_at'], name='analytics_a_created_a54b18_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClubAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_members', models.IntegerField(default=0)),
                ('new_members', models.IntegerField(default=0)),
                ('members_by_role', models.JSONField(default=dict)),
                ('events_hosted', models.IntegerField(default=0)),
                ('event_registrations', models.IntegerField(default=0)),
                ('avg_event_rating', models.FloatField(default=0.0)),
                ('resources_booked', models.IntegerField(default=0)),
                ('booking_hours', models.FloatField(default=0.0)),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('member_engagement', models.FloatField(default=0.0)),
                ('announcement_views', models.IntegerField(default=0)),
                ('document_downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='clubs.club')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['club', 'period_end'], name='analytics_c_club_id_6d4a94_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('login_count', models.IntegerField(default=0)),
                ('event_views', models.IntegerField(default=0)),
                ('event_registrations', models.IntegerField(default=0)),
                ('resource_bookings', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('announcements_viewed', models.IntegerField(default=0)),
                ('total_session_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_u_user_id_93eab3_idx'), models.Index(fields=['date'], name='analytics_u_date_2cb9d7_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
