# Generated by Django 6.0.1 on 2026-01-26 05:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('room', 'Room/Hall'), ('equipment', 'Equipment'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='other', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('specifications', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('booking_type', models.CharField(choices=[('auto', 'Auto-Approved'), ('manual', 'Requires Approval')], default='manual', max_length=20)),
                ('requires_training', models.BooleanField(default=False)),
                ('max_booking_duration', models.IntegerField(default=4, help_text='Maximum booking duration in hours')),
                ('min_advance_booking', models.IntegerField(default=1, help_text='Minimum hours before booking')),
                ('max_advance_booking', models.IntegerField(default=168, help_text='Maximum hours before booking (168 = 1 week)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_clubs', models.ManyToManyField(blank=True, related_name='accessible_resources', to='clubs.club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('ongoing', 'In Use'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('usage_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clubs.club')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_bookings', to='events.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('scheduled', 'Scheduled Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('other', 'Other')], default='scheduled', max_length=50)),
                ('description', models.TextField()),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('performed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='resources.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('condition_before', models.JSONField(default=dict)),
                ('condition_after', models.JSONField(blank=True, default=dict, null=True)),
                ('issues_reported', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='resources.resourcebooking')),
                ('check_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
                ('check_out_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='resourcebooking',
            index=models.Index(fields=['resource', 'start_time', 'end_time'], name='resources_r_resourc_ee2f78_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcebooking',
            index=models.Index(fields=['user'], name='resources_r_user_id_e157a4_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcebooking',
            index=models.Index(fields=['status'], name='resources_r_status_e309d0_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcebooking',
            index=models.Index(fields=['start_time'], name='resources_r_start_t_c3dc17_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status'], name='resources_r_status_f37b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['booking_type'], name='resources_r_booking_1f9d16_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcemaintenance',
            index=models.Index(fields=['resource', 'scheduled_start'], name='resources_r_resourc_49c70a_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcemaintenance',
            index=models.Index(fields=['status'], name='resources_r_status_295418_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceusagelog',
            index=models.Index(fields=['booking'], name='resources_r_booking_9ac418_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceusagelog',
            index=models.Index(fields=['check_in_time'], name='resources_r_check_i_6a0571_idx'),
        ),
    ]
